// GENERATED by `just gen-types` from core/aizen/api/protocol.py — do not edit.
/* eslint-disable */

export type ClientEvent = {
  t: "user_text";
  turnId?: string;
  text: string;
} | {
  t: "ptt_start";
} | {
  t: "ptt_stop";
} | {
  t: "interrupt_speech";
} | {
  t: "cancel_turn";
  turnId?: string;
} | {
  t: "confirm_response";
  requestId: string;
  approve: boolean;
  scope?: "once" | "session";
} | {
  t: "set_model";
  profile: string;
} | {
  t: "private_mode";
  on: boolean;
} | {
  t: "pong";
};

export type ServerEvent = {
  t: "session_state";
  state: string;
  seq: number;
  detail?: string | null;
} | {
  t: "orb_state";
  state: "IDLE" | "LISTENING" | "THINKING" | "SEARCHING" | "READING_FILE" | "CALCULATING" | "SPEAKING" | "ERROR";
  detail?: string | null;
} | {
  t: "route";
  domain: "finance" | "personal" | "web" | "chat" | "system" | "ambiguous";
  toolset?: string[];
  hint?: string | null;
} | {
  t: "transcript_partial";
  text: string;
} | {
  t: "transcript_final";
  text: string;
} | {
  t: "assistant_delta";
  turnId: string;
  text: string;
} | {
  t: "assistant_done";
  turnId: string;
  usage?: {
  promptTokens?: number;
  completionTokens?: number;
};
  verified?: boolean;
  domain?: "finance" | "personal" | "web" | "chat" | "system" | "ambiguous";
  tainted?: boolean;
} | {
  t: "tool_start";
  callId?: string;
  name: string;
  argsSummary?: string;
} | {
  t: "tool_end";
  callId?: string;
  name?: string;
  ok?: boolean;
  ms?: number;
  summary?: string;
  tainted?: boolean;
} | {
  t: "sources";
  turnId: string;
  items?: ({
  title: string;
  url?: string | null;
  path?: string | null;
  snippet?: string | null;
})[];
} | {
  t: "confirm_request";
  requestId: string;
  turnId: string;
  callId: string;
  tool: string;
  tier: string;
  risk?: "write" | "exec" | "network";
  summary: string;
  preview?: string | null;
  argsHash: string;
  tainted?: boolean;
  taintSources?: string[];
  expiresAt: string;
} | {
  t: "model_status";
  profile: string;
  loaded?: boolean;
  tokensPerSec?: number | null;
  ramMb?: number | null;
} | {
  t: "index_status";
  pending?: number;
  current?: string | null;
} | {
  t: "error";
  code: string;
  message: string;
  recoverable?: boolean;
  hint?: string | null;
} | {
  t: "ping";
};

export type ConfirmRequest = {
  request_id: string;
  turn_id: string;
  call_id: string;
  tool: string;
  tier: string;
  summary: string;
  preview?: string | null;
  args_hash: string;
  tainted?: boolean;
  taint_sources?: string[];
  expires_at: string;
};

export type ConfirmResponse = {
  request_id: string;
  approve: boolean;
  scope?: string;
};

export type VerifyResult = {
  ok: boolean;
  claims?: ({
  text: string;
  value: string;
  kind: "money" | "number" | "percent" | "count" | "date";
  currency?: string | null;
  matched_fact_id?: string | null;
  exempt?: boolean;
  exempt_reason?: string | null;
})[];
  unmatched?: string[];
  regenerated?: boolean;
  fell_back?: boolean;
};

export type SourceRef = {
  title: string;
  url?: string | null;
  path?: string | null;
  snippet?: string | null;
};

export type ErrorEvent = {
  t: "error";
  code: string;
  message: string;
  recoverable?: boolean;
  hint?: string | null;
};

export type SessionStateEvent = {
  t: "session_state";
  state: string;
  seq: number;
  detail?: string | null;
};

export type AssistantDoneEvent = {
  t: "assistant_done";
  turnId: string;
  usage?: {
  promptTokens?: number;
  completionTokens?: number;
};
  verified?: boolean;
  domain?: "finance" | "personal" | "web" | "chat" | "system" | "ambiguous";
  tainted?: boolean;
};
