#!/usr/bin/env python3
"""Generate the shared protocol artifacts from the Pydantic models.

Source of truth is ``aizen.api.protocol`` (architecture §6.2/§27/§28/§35). This
writes:

- ``protocol/json/<Model>.json`` — one JSON Schema per protocol model;
- ``protocol/schema.json`` — the same schemas keyed by model name;
- ``protocol/index.ts`` — dependency-free TypeScript type aliases.

TypeScript is emitted by a small in-repo emitter (no npm dependency, offline
safe). It covers exactly the JSON-Schema constructs Pydantic produces for these
models: objects, arrays, enums/consts, ``$ref``/``$defs`` and ``oneOf``/``anyOf``
unions.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "protocol"

_TS_PRIMITIVES = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
    "null": "null",
}


def _load_models() -> dict[str, Any]:
    sys.path.insert(0, str(ROOT / "core"))
    from aizen.api.protocol import PROTOCOL_MODELS

    return dict(PROTOCOL_MODELS)


def _schema(model: Any) -> dict[str, Any]:
    from pydantic import BaseModel, TypeAdapter

    if isinstance(model, type) and issubclass(model, BaseModel):
        schema = model.model_json_schema(by_alias=True)
    else:
        schema = TypeAdapter(model).json_schema()
    _require_discriminators(schema)
    return schema


def _require_discriminators(node: Any) -> None:
    """A tagged union's ``t`` field is always on the wire; Pydantic emits a
    default because the models set one for ergonomic construction. Make it
    required in the schema (and therefore in TypeScript)."""
    if isinstance(node, dict):
        props = node.get("properties")
        if isinstance(props, dict):
            tag = props.get("t")
            if isinstance(tag, dict) and "const" in tag:
                tag.pop("default", None)
                required = node.setdefault("required", [])
                if "t" not in required:
                    required.append("t")
        for value in node.values():
            _require_discriminators(value)
    elif isinstance(node, list):
        for value in node:
            _require_discriminators(value)


def _resolve(root: dict[str, Any], ref: str) -> dict[str, Any]:
    node: Any = root
    for part in ref.lstrip("#/").split("/"):
        node = node[part]
    return node


def _ts_type(schema: dict[str, Any], root: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ts_type(_resolve(root, schema["$ref"]), root)
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    for key in ("oneOf", "anyOf"):
        if key in schema:
            return " | ".join(dict.fromkeys(_ts_type(s, root) for s in schema[key]))
    if "allOf" in schema:
        return " & ".join(_ts_type(s, root) for s in schema["allOf"])
    node_type = schema.get("type")
    if isinstance(node_type, list):
        return " | ".join(dict.fromkeys(_TS_PRIMITIVES.get(t, "unknown") for t in node_type))
    if node_type == "array":
        items = schema.get("items", {})
        inner = _ts_type(items, root) if items else "unknown"
        if " | " in inner:
            inner = f"({inner})"
        return f"{inner}[]"
    if node_type == "object" or "properties" in schema:
        return _ts_object(schema, root)
    if node_type in _TS_PRIMITIVES:
        return _TS_PRIMITIVES[node_type]
    return "unknown"


def _ts_object(schema: dict[str, Any], root: dict[str, Any]) -> str:
    props: dict[str, Any] = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = ["{"]
    for name, prop in props.items():
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_ts_type(prop, root)};")
    if schema.get("additionalProperties"):
        extra = schema["additionalProperties"]
        value = "unknown" if extra is True else _ts_type(extra, root)
        lines.append(f"  [key: string]: {value};")
    lines.append("}")
    return "\n".join(lines)


def _typescript(models: dict[str, Any], schemas: dict[str, dict[str, Any]]) -> str:
    chunks = [
        "// GENERATED by `just gen-types` from core/aizen/api/protocol.py — do not edit.",
        "/* eslint-disable */",
        "",
    ]
    for name in models:
        schema = schemas[name]
        chunks.append(f"export type {name} = {_ts_type(schema, schema)};")
        chunks.append("")
    return "\n".join(chunks)


def main() -> int:
    models = _load_models()
    schemas = {name: _schema(model) for name, model in models.items()}

    OUT.mkdir(exist_ok=True)
    json_dir = OUT / "json"
    json_dir.mkdir(exist_ok=True)
    for name, schema in schemas.items():
        (json_dir / f"{name}.json").write_text(json.dumps(schema, indent=2) + "\n")
    (OUT / "schema.json").write_text(json.dumps(schemas, indent=2) + "\n")
    (OUT / "index.ts").write_text(_typescript(models, schemas))

    print(f"wrote {len(schemas)} schemas + index.ts to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
